const songs = [
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
  { name: hello, url: qbc, img: abc },
];
